# yaml-language-server: $schema=./zrb-config-schema.json

base_dir: /mnt/p1/ds1/bk/
age_public_key: age1ed9kad8ddqpjnt7k50tmxu8ngxte5ghmwsse7ckt6kdtvc7afpkqlj5ddk
s3:
  enabled: true
  bucket: my-backup-bucket
  region: us-east-1
  prefix: zfs-backups/
  endpoint: ""
  storage_class:
    manifest: STANDARD
    backup_data:
      - DEEP_ARCHIVE # Level 0 (full backup)
      - DEEP_ARCHIVE
      - DEEP_ARCHIVE
      - GLACIER
  retry:
    max_attempts: 8
tasks:
  - name: example_task
    description: Example backup task
    pool: p1
    dataset: temp
    enabled: true
