# yaml-language-server: $schema=https://raw.githubusercontent.com/ziteh/zfs-remote-backup/refs/heads/main/docs/config-schema.json

base_dir: /mnt/pool/dataset/zrb/
age_public_key: age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
s3:
  enabled: true
  bucket: my-backup-bucket
  region: us-east-1
  prefix: zfs-backups/
  endpoint: "" # Leave empty for AWS S3, or specify custom endpoint for S3-compatible services
  storage_class:
    manifest: STANDARD
    backup_data:
      - DEEP_ARCHIVE # Level 0 (full backup)
      - DEEP_ARCHIVE
      - DEEP_ARCHIVE
      - GLACIER
  retry:
    max_attempts: 8
tasks:
  - name: example_task
    description: Example backup task
    pool: pool
    dataset: temp
    enabled: true
