base_dir: /tmp/zrb_backups/
age_public_key: age1ed9kad8ddqpjnt7k50tmxu8ngxte5ghmwsse7ckt6kdtvc7afpkqlj5ddk
s3:
  enabled: false
  bucket: my-backup-bucket
  prefix: zfs-backups
  region: us-east-1
  endpoint: "" # Leave empty for AWS S3, or specify custom endpoint for S3 compatible services
  storage_class: # Options: STANDARD, INTELLIGENT_TIERING, STANDARD_IA, ONEZONE_IA, GLACIER, DEEP_ARCHIVE, GLACIER_IR
    full_backup: DEEP_ARCHIVE
    diff_backup: GLACIER
    incr_backup: STANDARD_IA
    manifest: STANDARD
tasks:
  - name: daily_backup
    description: Daily backup task
    pool: testpool
    dataset: backup_data
    enabled: true
  - name: weekly_backup
    description: Weekly backup task
    pool: testpool
    dataset: backup_data
    enabled: false
